### ISSUE TITLE
Automatically adjust contrast/brightness on opened images

### ISSUE THREAD

**Issue by thomasaarholt** [JJPPeters/Strainpp#3]
I'm struggling to formulate myself, but currently when I load an image (say, a 16-bit TIF), the plotted image shows greyscale values of [0, image_max], rather than [image_min, image_max]. 
Here's an example with a "raw" image, which has intensities ranging from 18600 to 38200.
![image](https://user-images.githubusercontent.com/2721423/49526280-ca316480-f8af-11e8-9d3d-c3069faa00ee.png)

If I manually reduce the intensities of the image by 18600, so the range is from 0 to 19600, then the image looks like this:

![image](https://user-images.githubusercontent.com/2721423/49526460-2300fd00-f8b0-11e8-8db9-0ba2d34af41c.png)

**Comment by JJPPeters** [comment]
Hi,

Thanks for this, it's a problem I had noticed but never had the impetus to solve it.

The problem is simply solved by passing 'true' to the `rescaleDataRange` method from the class `QCPColorMap` when it is called. I'll put it in a new release soon if you aren't compiling it yourself.

To elaborate on the problem:
`QCPColorMap` updates the data ranges when you set the data, but only in an expanding fashion (the max will only get bigger, the min will only get smaller). I'm guessing the default values are 0, so an image with all data greater than 0 will never update the minimum. I had naively assumed `rescaleDataRange` would do this automatically.

Cheers,
Jon.

**Comment by thomasaarholt** [comment]
Thanks for the response! This is nice software!

**Comment by JJPPeters** [comment]
I have pushed this to the master branch and released v1.5 with this fix.

Please reopen this if there are still problems.

Cheers,
Jon.
